name = "Django"
kickstart_version = 1
ignore = [
    "{{project_name}}/.venv",
    "{{project_name}}/node_modules",
    "{{project_name}}/db.sqlite3",
]
directory = "{{project_name}}"
copy_without_render = ["*.html"]

[[variables]]
name = "project_name"
default = "my_project"
prompt = "What is the name of this project?"
validation = "^([a-zA-Z][a-zA-Z0-9_-]+)$"


[[variables]]
name = "database"
default = "sqlite"
prompt = "Which database do you want to use?"
choices = ["postgres", "mysql", "sqlite"]