version: '3.1'
services:
  database:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: {{ project_name }}
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  mailpit:
    image: axllent/mailpit
    ports:
      - 8025:8025
      - 1025:1025